include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # Desactivar reglas que pueden ser demasiado estrictas para empezar
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    prefer_relative_imports: false
    use_setters_to_change_properties: false
    
    # Activar reglas adicionales
    prefer_single_quotes: true
    avoid_redundant_argument_values: true
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.gr.dart"
    - "lib/generated/**"
  
  errors:
    invalid_annotation_target: ignore
